//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaitanEt.MainBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int Id_Status { get; set; }
        public string Name_Status { get; set; }
    }
}
