//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaitanEt.MainBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_Product { get; set; }
        public string Name_Product { get; set; }
        public byte[] ImageSource { get; set; }
        public Nullable<System.DateTime> LastDateEdit { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
